version: "3"

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ticketing
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    tty: true
    volumes:
      - ./mysqldb:/var/lib/mysql
    user: mysql